/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package birincidonem;

/**
 *
 * @author Meyrem
 */
public class cbagli extends javax.swing.JFrame {
       cBListe L;
    /**
     * Creates new form cbagli
     */
    public cbagli() {
        initComponents();
        L = new cBListe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        basaekle = new javax.swing.JButton();
        bastansil = new javax.swing.JButton();
        sonaEkle = new javax.swing.JButton();
        sondanSil = new javax.swing.JButton();
        listele = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        elemanAra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sayı  :");

        basaekle.setText("Başa Ekle");
        basaekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basaekleActionPerformed(evt);
            }
        });

        bastansil.setText("Baştan sil");
        bastansil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bastansilActionPerformed(evt);
            }
        });

        sonaEkle.setText("Sona ekle");
        sonaEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonaEkleActionPerformed(evt);
            }
        });

        sondanSil.setText("Sondan sil");
        sondanSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sondanSilActionPerformed(evt);
            }
        });

        listele.setText("Listele");
        listele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeleActionPerformed(evt);
            }
        });

        jLabel2.setText("Dizi :");

        elemanAra.setText("Eleman Ara");
        elemanAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemanAraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sonaEkle)
                                .addGap(18, 18, 18)
                                .addComponent(sondanSil))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(basaekle)
                                .addGap(18, 18, 18)
                                .addComponent(bastansil))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listele)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(elemanAra)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basaekle)
                    .addComponent(bastansil))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sonaEkle)
                    .addComponent(sondanSil))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listele)
                    .addComponent(elemanAra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void basaekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basaekleActionPerformed
     int sayı = Integer.parseInt(jTextField1.getText());
     cEleman yeni = new cEleman(sayı);
     L.basaEkle(yeni);
     jLabel2.setText(L.listele());
    }//GEN-LAST:event_basaekleActionPerformed

    private void bastansilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bastansilActionPerformed
     cEleman sonuc = L.bastanSil();
        if (sonuc!=null) {
            jLabel2.setText(L.listele());
        } else {
            jLabel2.setText("Liste boş");
        }
    }//GEN-LAST:event_bastansilActionPerformed

    private void sonaEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonaEkleActionPerformed
        int sayi = Integer.parseInt(jTextField1.getText());
        cEleman yeni = new cEleman(sayi);
        L.sonaEkle(yeni);
        jLabel2.setText(L.listele());
    }//GEN-LAST:event_sonaEkleActionPerformed

    private void sondanSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sondanSilActionPerformed
          cEleman sonuc=L.sondanSil();
           if (sonuc!=null) {
               jLabel2.setText(L.listele());
        } else {
               jLabel2.setText("Liste Boş");
        }
        
    }//GEN-LAST:event_sondanSilActionPerformed

    private void listeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeleActionPerformed

        jLabel2.setText(L.listele());
    }//GEN-LAST:event_listeleActionPerformed

    private void elemanAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemanAraActionPerformed

        
    }//GEN-LAST:event_elemanAraActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cbagli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cbagli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cbagli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cbagli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cbagli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton basaekle;
    private javax.swing.JButton bastansil;
    private javax.swing.JButton elemanAra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton listele;
    private javax.swing.JButton sonaEkle;
    private javax.swing.JButton sondanSil;
    // End of variables declaration//GEN-END:variables
}
